# 190110



### 사용자 모듈

실행순서

- 위에서부터(top-level) 실행

```python
# __name__  ? :  파이썬 스크립트를 그래도 실행했을 때 모듈로써 실행하고있는건지, 아니면 python.py로 실행하고 있는지를 판단
if(__name__ == "__main__"):
    print("a.py를 직접 실행")
else:
    print("import a.py")
```

- top-level에 print() 가 찍혀있으면 import하면 출력됨

`top-level` = indent가 적용되지 않은 모든 code



## python

## 오류(Errors) & 예외처리(Exceptions)



### 문법에러(Syntax Error)

- 뭔가 빠뜨렸거나(`,`, `:`, `""`등등) 잘못적었을 때 발생
- `^`  표시로 틀린 위치를 표시해 주지만, 정확한 위치는 아니고 해당 line까지는 알 수 있다

```python
# syntax error예
File "<ipython-input-1-2ef577c90b10>", line 4
    else
        ^
SyntaxError: invalid syntax

# EOL error
File "<ipython-input-2-c70f4029c163>", line 3
    print("aaaaaaa)
                   ^
SyntaxError: EOL while scanning string literal

# EOF error
File "<ipython-input-3-3a223444d941>", line 2
  print("asdfsdf"
                 ^
SyntaxError: unexpected EOF while parsing        
```



### 에러 종류

```python
# ZeroDivisionError 
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-5-1a1c9c3dae95> in <module>
      1 # ZeroDivisionError를 확인해봅시다.
----> 2 10 / 0

ZeroDivisionError: division by zero
    
# NameError : 사용하지 않았던 변수를 사용했을 때 발생
NameError                                 Traceback (most recent call last)
<ipython-input-6-2516ed2be577> in <module>
      1 # NameError를 확인해봅시다.
----> 2 print(hello)

NameError: name 'hello' is not defined  # hello가 정의되지 않았다
    
# TypeError : 타입이 다르다
TypeError                                 Traceback (most recent call last)
<ipython-input-7-a95aca245afd> in <module>
      1 # TypeError를 확인해봅시다.
----> 2 1 + "5"

TypeError: unsupported operand type(s) for +: 'int' and 'str'
        # +는 int와 str를 더할 수 없다
        
# 함수 호출과정의 TypeError
TypeError                                 Traceback (most recent call last)
<ipython-input-8-47bdb1560f34> in <module>
      1 # 함수 호출과정에서 TypeError도 발생하게 됩니다. 확인해봅시다.
----> 2 round()

TypeError: type str doesn't define __round__ method
    # round method가 없다

# 필수 argument가 누락된 TypeError
### 자주발생하는 오류 중 하나
TypeError                                 Traceback (most recent call last)
<ipython-input-10-621ab5efe8b1> in <module>
      1 # 함수호출 과정에서 다양한 오류를 확인할 수 있습니다. : 필수 argument 누락
      2 import random
----> 3 random.sample(range(1,46))
	---> random.sample(range(1,46),6) 으로 수정
TypeError: sample() missing 1 required positional argument: 'k'
        # k라는 argument하나가 빠졌다
        
        
# argument가 많은 경우 TypeError
TypeError                                 Traceback (most recent call last)
<ipython-input-11-1d41a4b73a73> in <module>
      1 # 함수호출 과정에서 다양한 오류를 확인할 수 있습니다. : argument 많은 경우
----> 2 random.choice(range(1,46),6)
	---> random.choice(range(1,46))
TypeError: choice() takes 2 positional arguments but 3 were given
    # 2개만 필요한데 3개가 입력이 되었다
    
    
#ValueError 1 : 자료형에 대한 type은 올바르지만, 값이 적절하지 않기 때문에 발생
ValueError                                Traceback (most recent call last)
<ipython-input-14-789240015774> in <module>
      1 # ValueError를 확인해봅시다.
----> 2 int("3,5")
	
ValueError: invalid literal for int() with base 10: '3,5'
        # 
        
        
#ValueError 2 : 값이 적절하지 않는 경우 발생, 값이 없는데 찾으려고 하는 경우
TypeError                                 Traceback (most recent call last)
<ipython-input-15-e21fa6a55961> in <module>
      1 # ValueError를 확인해봅시다.
      2 a = [1,2]
----> 3 a.index[3]

TypeError: 'builtin_function_or_method' object is not subscriptable
 

#IndexError
### 자주발생
IndexError                                Traceback (most recent call last)
<ipython-input-16-850c79f05d56> in <module>
      1 # IndexError를 확인해봅시다.
      2 a = [1,2,3]
----> 3 a[5]

IndexError: list index out of range
    # list의 index의 범위를 벗어남

    
#KeyError
KeyError                                  Traceback (most recent call last)
<ipython-input-18-d7a0c1e37db5> in <module>
      1 # KeyError를 확인해봅시다.
      2 my_dict = {'today':"2019-01-10"}
----> 3 my_dict["yesterday"]

KeyError: 'yesterday'
    # 해당하는 키가 없다
    
    
#ModuleNotFoundError
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-19-4b9a34fac305> in <module>
      1 # ModuleNotFoundError를 확인해봅시다.
----> 2 import mymodule

ModuleNotFoundError: No module named 'mymodule'
    # 해당하는 모듈이 없다
    
    
    
#ImportError : 해당하는 모듈을 찾았지만, 그 안에 해당하는게 없을 때 발생
ImportError                               Traceback (most recent call last)
<ipython-input-20-2df40018a06f> in <module>
      1 # ImoprtError를 확인해봅시다.
----> 2 from bs4 import bbb

ImportError: cannot import name 'bbb'   

    
    
    
#KeyboardInterrupt
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-21-7223299ee06f> in <module>
      1 # KeyboardInterrupt를 확인해봅시다.
      2 while(True):
----> 3     continue

KeyboardInterrupt: 
    # 코드를 돌릴 때 ctrl + c (강제정지, interrupt를 주는것)
    # 멈추고 해당 오류 발생
```



### 예외(Exceptions)처리

`try`  `except`  구문을 이용하여 예외 처리

- 에러명을 입력할 때 대소문자에 유의해서 처리해야 됨

```python
# 사용자가 문자열을 넣어 해당 오류(ValueError)가 발생하면, 숫자를 입력하라고 출력
try:
    num = (input("값을 입력해주세요 : "))
    print(int(num))
except(ValueError):
    print("숫자를 입력해 바보야")
```

```python
# 100을 사용자가 입력한 값으로 나눈 후 출력하는 코드를 문자열일때와 0일때 모두 처리
try:
    num = input("숫자를 입력하면 100을 나눠 줄게 :")
    print(100/int(num))
except(ValueError, ZeroDivisionError):
    print("으이그 바보야")
    

# 각각 다른 오류 출력 가능
try:
    num = input("숫자를 입력하면 100을 나눠 줄게 :")
    print(100/int(num))
except(ValueError):
    print("으이그 바보야 숫자넣어")
except(ZeroDivisionError):
    print("0은 왜넣냐 이놈아")
except:
    print("뭔진 모르지만 에러가났네?")
    
# 중요한 내용은 순차적으로 수행되므로, 가장 적은 범주부터 시작해야 함    
try:
    num = input("숫자를 입력하면 100을 나눠 줄게 :")
    print(100/int(num))

except(Exception):  # 모든 에러 처리
    print("뭔진 모르지만 에러가났네?")
except(ValueError): # ValueError만 처리
    print("으이그 바보야 숫자넣어")
except(ZeroDivisionError): # ZeroDivisonError만 처리
    print("0은 왜넣냐 이놈아")
```

### 에러 문구 처리

```python
try:
    a = [1,2,3]
    print(a[5])
except(IndexError) as e:
    print(f"범위밖 탐색 : {e}")
    # 해당 오류내용을 e에 담아 출력해줌
	# 출력은 >>> 범위밖 탐색 : list index out of range
```

### 에러 else

```python
try:
    a = [1,2,3]
    b = a[1]
except(IndesError):
    print("범위밖에서 탐색") # 에러뜨면 여기
else:
    print(b+10) # 에러안뜨면 여기
```

### finally

- 반드시 수행해야 하는 문장을 finally에 넣어서 

```python
try:
    a = {"python" : "good"}
    a["java"]
except(KeyError) as e:
    print(f"{e}는 딕셔너리에 없는 키 입니다")
finally:
    print(a)
```

### else와 finally의 다른첨

- finally는 오류가 발행해도 출력



### 예외 발생시키기

- 강제적으로 에러를 발생시키기

```python
raise ValueError

raise ValueError("값이 잘못 된거 같아요")

ValueError                                Traceback (most recent call last)
<ipython-input-54-5d6952da23e5> in <module>
      1 # 인자를 넘겨줄 수도 있습니다.
----> 2 raise ValueError("값이 잘못 된거 같아요")

ValueError: 값이 잘못 된거 같아요

```



## OOP(Object-Oriented Programming)

### 클래스 / 인스턴스 / 매서드

```python
a = 1+5j
print(type(a))
>>> <class 'complex'>
# 'complex' 클래스

print(a.real, a.imag)
# a라는 인스턴스를 통해서 real / imag라는 매서드를 호출
```

### 클래스

```python
class ClassName:
    # ClassName ---> camelcase
    # 클래스이름은 첫시작은 대문자, 각각의 단어가 구분될 때 대문자로
    # Snakecase : my_dict_name 
```

```python
class Person:
    name = "문동식"
    # 클래스 안에 정의된 함수 = 메서드
    def greeting(self):
        print(f"hello, {self.name}")
# self : 인스턴스화 된 자기자신을 뜻함
```

### 인스턴스

```python
# iu라는 변수에 있는 친구가 Person과 같은 instance니?
iu = Person()
iu.greeting()
iu.name
iu.name = "이지은"
# Person.name(iu) = "이지은" 과 같음
isinstance(iu,Person)
>>> type(iu) ====> __main__.person
# iu 자체는 인스턴스 객체
# iu만 찍으면 정보를 찾을 수 없음
# iu.name 이렇게 접근해야 찾을 수 있다

```

```python
class Person():
    name=  "기본이름"
    
    def greeting(self):
        print(f"안녕하세요! {self.name}입니다 !")
        
    def __str__(self):
        return f"사람 : {self.name}"
    def __repr__(self):
        return f"person : {self.name}"
    
daniel = Person()
daniel.name = "다니엘"
print(daniel)
>>> 사람 : 다니엘
daniel
>>> person : 다니엘
```



### 두번째 원을 만들고 x,y좌표를 (5,-5)로 이동시킨 후 첫번째 원과 외접하는 조건의 반지름을 구하세요

```python
class Circle:
    pi = 3.14
    x = 0
    y = 0
    r = 0
    
    def area(self):
        return self.pi * self.r * self.r
    
    def circumference(self):
        return 2 * self.pi * self.r
    
    def center(self):
        return (self.x, self.y)
    
    def move(self, x, y):
        self.x = x
        self.y = y
```

```python
my_circle2 = Circle()
my_circle2.x, my_circle2.y = 5, -5

my_circle2.x = (my_circle.x - my_circle2.x)**2
my_circle2.y = (my_circle.y - my_circle2.y)**2
my_circle2.r = (my_circle2.x + my_circle2.y)**0.5
my_circle2.r = my_circle2.r - my_circle.r
print(my_circle2.r)
```



















